###### POSTGRES SQL DATABASE, REDIS and PGADMIN ########
version: '3.8'
services:
#    postgres:
#        image: postgres:14-alpine
#        container_name: postgres
#        ports:
#            - 5432:5432
#        volumes:
#            - ./postgres_data:/var/lib/postgresql/data
#        environment:
#            POSTGRES_PASSWORD: postgres
#            POSTGRES_USER: postgres
#            POSTGRES_DB: alura_series
#    pgadmin:
#        image: dpage/pgadmin4
#        container_name: pgadmin
#        depends_on:
#            - postgres        
#        environment:
#            PGADMIN_DEFAULT_EMAIL: 'fpzitellij@gmail.com'
#            PGADMIN_DEFAULT_PASSWORD: 'teste'
#        ports:
#            - 16543:80
#        volumes:
#            - ./pgadmin_data:/pgadmin4/servers.json
    redis:
        image: redis:latest
        container_name: redis
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./redis_data:/data
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        environment:
            REDIS_PASSWORD: redis
            REDIS_PORT: 6379
            REDIS_DATABASES: 16
